jina-ai/clip-as-service

README.md, server/bert_serving/server/__init__.py
**Code greatly inspired by #118** 
It's basically the same pull request, but you can choose the location of file using an environment variable. The default behavior (the environment variable is not set) is the same as previously : tmp file are created on the current folder.
**Solve #73** (I was indeed talking about socket tmp files generated ^^)
_Note : the choice of the location is done through environment variable. In my opinion, it's less invasive than command line argument._
=> Tmp file (generated by ipc socket) location choice 

client/MANIFEST.in, client/bert_serving/client/__init__.py, server/MANIFEST.in
python 2 user encounter unicode error when using `bc.encode`
=> fix support for python2

client/bert_serving/client/__init__.py, server/bert_serving/server/__init__.py, server/bert_serving/server/graph.py, server/bert_serving/server/helper.py, server/bin/bert-serving-start
- add timeout to BertClient, fix #134 
- fix `-version` in argparser
- fix device map logic on gpu and cpu
- add `-verbose` for controlling log level
- move msg size to client side for better efficiency
- optimize imports, adding `__all__`
=> add timeout to BertClient

README.md, server/bert_serving/server/__init__.py, server/bert_serving/server/helper.py
a high priority queue/socket is added to ensure small batch requests won't be blocked by super-large batch requests. Previously, if the service is busy handling a super large batch from one client, another client would have to wait until the large batch is fully finished.
=> Add high priority queue

client/bert_serving/client/__init__.py
* change note: only set `check_version=False` will still send message to server, need set `check_length=False`.
* call BertClient.close() will hang at `self.context.term()`, if server_status is quried from server and timeout. Refer to [StackoverFlow #1](https://stackoverflow.com/questions/46029965/zeromq-blocked-in-a-context-term-call-why-how-to-prevent) and [StackoverFlow #2](https://stackoverflow.com/questions/44273941/python-script-not-terminating-after-timeout-in-zmq-recv), I set zmq.LINGER to zero, and it worked. But I'm not sure is this option will lead to any other problem, so pls help to review, thx.
=> For Client: update note and set zmq.LINGER zero

client/bert_serving/client/__init__.py
- use `warnings` pkg to print out length warning
=> change default timeout to -1

server/bert_serving/server/graph.py, server/bert_serving/server/helper.py
serving multiple different bert models on a single machine will generate too many tmp file under /tmp.
I wondering is it possible to add an argument to config where the graph temp file will store
=> add argument to config tmp file path

client/bert_serving/client/__init__.py
Inherit from `BertClient` and use super with the conventional syntax.
Example:
```
class MyBertClient(BertClient):
def __init__(self, *args, **kwargs):
super(BertClient, self).__init(*args, **kwargs)
...
```
=> Fix #247 Change BertClient Class to Conform with new-style

client/bert_serving/client/__init__.py
There was an error because of previous implementation (for example, in case of batch with one empty line bc was ignored instead of appending it back to bc_available). I believe that context manager will solve this kind of problem.
=> use context manager for access to bc_available

README.md, client/README.md, docs/tutorial/simple-search.rst, example/example8.py, server/README.md
The embeddings generated by this library have different norms depending on the input. In my understanding, using a simple dot product as a scoring function for search isn't sensible because the norm of the vector affects the output irrespective of relatedness. 
Cosine similarity is a more suitable metric. But, since the query is fixed across all comparisons, we can safely ignore the query's norm. Thus, a simple solution is to normalize the dot products with the norm of the document.
Qualitatively, the results I get from simple dot products are pretty bad, whereas they're as expected with the normalized version.
=> Simple dot products aren't sensible scoring functions

server/bert_serving/server/__init__.py
When server ports are exposed to the public network, there is a risk of malicious requests or scans. The server will crash when the number of frames is satisfied but the last two frames are not integer. So, I added two assert statements to avoid this problem.
=> Add request verification to avoid crash

README.md, server/bert_serving/server/__init__.py, server/bert_serving/server/helper.py
Added server command line option for cased tokenization, as required to keep the casing and accented letters in the pretrained multilingual cased model and other models.
Default behavior is not changed.
Server command line option -cased_tokenization will initialize the tokenizer with do_lower_case=False so that the text doesn't get lowercased and accented letters changed to non-accented versions.
Fixes #328 , fixes #284
=> Added server command line option for cased tokenization

client/bert_serving/client/__init__.py, server/bert_serving/server/__init__.py, server/bert_serving/server/helper.py
I think this will fix issue #400.
By default creating a new client requests server config to check versions, this also builds and sends the server statistics which the client does not use. I've broken it up into `SHOW_CONFIG` and `SHOW_STATUS` so statistic object will only be created/sent when you explicitly request it from client/http endpoint.
I believe the client keyed statistic dicts continue to grow unbounded as long as new clients are created using up memory and slowing down code path. I've replaced them with a dict-like class that takes a set size limit. When the capacity is reached it evicts entries using LRU policy; evicted entries are added to aggregate stats fields for generating info.
These stats may be slightly off if you use more than the capacity of clients simultaneously, …
=> Improve statistics performance

README.md, client/README.md, docs/section/faq.rst, server/README.md
This is a quick pull request to change instances of `bert_serving_start` to `bert-serving-start`, which seems to be the correct entrypoint for the module!
```python
'console_scripts': ['bert-serving-start=bert_serving.server.cli:main',
```
I would bet it used to be the other one? And then someone decided that dashes > underscore :)
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
=> Updating bert_serving_start to bert-serving-start

server/bert_serving/server/__init__.py, server/bert_serving/server/bert/extract_features.py, server/bert_serving/server/helper.py
I want to add this because I need a long sentence representation. My way is split sentence and through bert and combine it. It works fine in experiments. 
Maybe the name of config is not good, modify it if you want
=> Add a config which can let bert not add CLS and SEP automatically

client/README.md
fix issue #394
BertServer.shutdown() should use with args.
so fix readme
=> fix readme about how to use BertServer.shutdown with static method

server/bert_serving/server/graph.py
in the original Google BERT paper, after fine-tuning is done on a classification task, the CLS token is pooled with a single tanh layer before it is sent to the linear classifier head. this PR adds an additional pooling strategy that uses the CLS pooling already in the BERT graph.  @hanxiao
=> added pooling strategy for CLS_POOLED

server/bert_serving/server/bertApi.openapi.yaml, server/bert_serving/server/http.py, server/setup.py
Hello,
I have integrated [SwaggerUI](https://swagger.io/tools/swagger-ui/) into Flask http server and defined a [OpenAPI contract definition](https://swagger.io/docs/specification/about/) to support testing the API from browser and [generating clients for various languages.](https://github.com/OpenAPITools/openapi-generator) 
Open issues:
- Readme should be updated.
- Maybe it could be optional?
- Tokenization result is not present (it wasn't in http implementation either so it is not in contract)
- I have entered my info into contract, feel free to change it to something more appropriate
I am opened to feedback.
Thank you,
Filip
=> OpenAPI contract and SwaggerUI support for bert-as-service

docker/Dockerfile, docker/entrypoint.sh
This PR makes three changes to the Docker deployment:
- The service is installed with HTTP support and started with the HTTP endpoint running. Given the image comes out several gigabytes in size, the extra image size of doing this is negligible and if the HTTP endpoint is not needed then the user can simply choose not to expose the port (which needs `-p 8125:8125` on the docker command line)
- Since all dependencies and code are installed with the `pip` command, the copying of the full source (and documentation!) into the Docker image has been removed. This both makes a slightly smaller image and improves both build speed and build cachability.
- A `HEALTHCHECK` setting has been added to the `Dockerfile` so that Docker will report the status of the service in `docker ps`.
=> Improvements to Docker deployment

docker/Dockerfile
Without the app directory the building of docker image fails.
=> Update Dockerfile to make the directory "app"

plugin/dashboard/bindings.js
This fixes the issue with the dashboard: it now loads the high level statistics for a locally running BERT service.
=> Changed serverUrl to what bert service responds to

client/setup.py, server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_torch.py, server/setup.py, setup.py
remove unused main methods in executors, unify keywords in setup.py
=> refactor: remove unused main unify keywords

client/clip_client/client.py, server/setup.py, tests/test_simple.py
The following pip install cannot work on MacOS
```
pip install "clip-server[onnx]"
```
The `onnxruntime-gpu` is not available for MacOS.
=> fix: ignore onnxruntime-gpu on macos

server/clip_server/model/clip.py, server/clip_server/model/clip_onnx.py, tests/test_server.py
resume downloading of the model. Now if the downloading is interrupted (not completed) at the first time, the service cannot be started anymore.
=> fix: download with resume

server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_torch.py, server/clip_server/executors/clip_trt.py, tests/test_ranker.py, tests/test_tensorrt.py
TODO:
- explain how to config `logit_scale`
- from pre-trained model (same as torch implementation)
- could be a static global variable or a parameter (this PR in onnx and tensorrt)
=> feat: add ranker endpoint for all backends

server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_tensorrt.py, server/clip_server/executors/clip_torch.py, server/clip_server/onnx-flow.yml, server/clip_server/tensorrt-flow.yml, server/clip_server/torch-flow.yml, server/setup.py
WIP, blocked by https://github.com/jina-ai/jina/pull/4526
=> feat: add monitoring

server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_tensorrt.py, server/clip_server/executors/clip_torch.py, server/clip_server/onnx-flow.yml, server/clip_server/tensorrt-flow.yml, server/clip_server/torch-flow.yml
Does not make sense to enable monitoring default, will remove monitoring from default YAML config. The monitoring port should be provided by the user depending on their environment in production.
=> fix: better monitoring

client/clip_client/client.py, server/clip_server/executors/clip_hg.py, server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_tensorrt.py, server/clip_server/executors/clip_torch.py, server/clip_server/executors/helper.py, tests/test_hg.py, tests/test_simple.py
Reverts jina-ai/clip-as-service#748
=> Revert "feat: add traversal paths"

docs/requirements.txt
Failed to build docs due to breaking changes of markdown3.4. More details at https://github.com/ryanfox/sphinx-markdown-tables/issues/36
=> chore: fix markdown-table extention

client/clip_client/client.py, client/clip_client/helper.py
This pr allow users to pass credential for HTTP and GRPC, and use it for authentication when getting request from server
=> feat: allow credential in client

client/clip_client/client.py, docs/user-guides/client.md
This pr allows the user to select the model in the client when multiple models are running.
Sample usage:
```
from clip_client import Client
c = Client(xxx)
c.encode(xxx, parameters={'model': 'RN50'})
c.rank(xxx, parameters={'model': 'RN50'})
```
=> feat: allow model selection in client

server/clip_server/model/mclip_model.py, server/clip_server/model/openclip_model.py, server/clip_server/model/pretrained_models.py, server/setup.py
to support independent download process and make precision adapted to device to solve VRAM issue
=> feat: update openclip loader

server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_tensorrt.py, server/clip_server/executors/clip_torch.py
This PR fix the following things:
=> fix: no allow client to change server batch size

server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_tensorrt.py, server/clip_server/executors/clip_torch.py, tests/test_simple.py
This pr adapts the newest wording of parameter access_paths to improve narrative.
Similar to https://github.com/jina-ai/executor-text-dpr-encoder/pull/7
=> feat: replace traversal_paths with access_paths

.github/README-exec/onnx.readme.md, .github/README-exec/torch.readme.md, client/setup.py, scripts/benchmark.py, server/clip_server/model/clip_onnx.py, server/setup.py
this pr updates model list in jina hub readme
=> docs: update hub readme

server/clip_server/executors/helper.py, tests/test_helper.py
In previous versions, when a doc contains both text and URI fields, clip_server will treat it as an image doc.
In this pr we encode text first since the text is a [content attribute](https://docarray.jina.ai/fundamentals/document/attribute/#content-attributes) and URI is only a source of content. 
So now when a doc has text and URI fields, we will consider it as a text doc.
=> feat: encode text first when both text and uri are presented

client/clip_client/client.py, tests/test_client.py
<s>When the doc to be encoded is broken (contains broken URIs, incomplete files, etc.), the server will raise an error and the whole encoding process is thus stopped.
This is especially infeasible for large encoding tasks with thousands or even millions of docs.
In this pr, we improve the user experience by skipping such broken docs and printing warning messages instead.
The whole process is not interrupted.
Users can thus decide whether to proceed with this task or stop.
After several discussions with team members, we decide to add a warning at the very beginning of the client to suggest users use moderate-size documents when the input is too large since there is always one more case to consider
=> feat: add warning if input is too large

client/clip_client/client.py, server/clip_server/executors/helper.py, tests/conftest.py, tests/test_asyncio.py, tests/test_helper.py, tests/test_ranker.py, tests/test_simple.py
If the user encodes a document with uri and no blob, the current implementation will load the blob in the client and send it to the server.
This pr saves the bandwidth by not sending back blob from the server
I ran some tests to see the benefit we have from this change.
```{python}
from clip_client import Client
from jina import Document, DocumentArray
c = Client('grpc://0.0.0.0:5001')
def data_gen():
for _ in range(80):
yield Document(uri='toy.png')
r = c.encode(data_gen(), batch_size=8, show_progress=True)
r.summary()
```
- Server config: default minibatch_size=32, model: Vit-L/14@336px, replicas: 3
- Client config: default batch_size=8, input DocumentArray size=80 with each Document having a URI of an image of size ~1.5MB
- Before: send 90MB, recv 90MB, cost 3-13min (Server hosted on …
=> feat: do not send blob from server when it is loaded in client

docs/user-guides/server.md, server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_tensorrt.py, server/clip_server/executors/clip_torch.py
This pr adds docstring to CLIP executors
Also fix some typo and misinformation in the docs
=> chore: update executor docstring

server/clip_server/model/clip_model.py, server/clip_server/model/clip_onnx.py, server/clip_server/model/clip_trt.py
We did not list all available models when the user input a wrong model name in torch runtime previously, this pr fix this
this pr also reformat the error msg, it now looks like
=> chore: improve model not found error msg

README.md
update the readme to use the new service hosted at `api.clip.jina.ai`
=> fix(readme): use new demo server

client/clip_client/client.py, tests/test_asyncio.py, tests/test_client.py, tests/test_ranker.py, tests/test_server.py, tests/test_simple.py, tests/test_tensorrt.py
This PR introduces the following changes to CAS:
**Notice**: the result is not complete if the ids of input are not unique
Basic tests for memory usage:
```{python}
from clip_client import Client
from docarray import Document, DocumentArray
import psutil
def func():
c = Client('grpc://0.0.0.0:51000')
da = DocumentArray()
for _ in range(8):
da.append(Document(uri='toy.jpeg'))
r = c.encode(da)
return da, r
if __name__ == '__main__':
mem = []
for _ in range(10):
a, b = func()
mem.append(psutil.Process().memory_info().rss / 1024**2)
print(mem)
print(sum(mem)/len(mem))
```
Send 10 batches of images with each batch_size = 8
before (no in-place) in MB: 
> 76.23828125, 76.98046875, 78.0234375, 78.99609375, 79.8125, 79.953125, 73.06640625, 73.42578125, 73.6484375, 74.0703125
> avg 76.421484375 …
=> feat: in-place result in clip_client; preserve output order by uid

docs/user-guides/server.md, server/clip_server/model/clip_onnx.py, server/clip_server/model/model.py, server/clip_server/model/pretrained_models.py, server/clip_server/onnx-flow.yml, server/clip_server/torch-flow.yml
This pr supports 4 new clip models introduced by https://laion.ai/blog/large-openclip/
- ViT-B-32::laion2B-s34B-b79K (PyTorch+ONNX)
- ViT-L-14::laion2B-s32B-b82K (PyTorch+ONNX)
- ViT-H-14::laion2B-s32B-b79K (PyTorch)
- ViT-g-14::laion2B-s12B-b42K (PyTorch)
It also sets timeout to 30 min in torch and onnx runtime since we have larger model files now
=> feat: support B/32, L/14, H/14, and g/14 trained on LAION-2B

docs/user-guides/server.md, server/clip_server/model/clip_onnx.py, server/clip_server/model/pretrained_models.py, tests/test_model.py
This pr adapts the naming convention of open clip to give a consistent list of model names. This can reduce confusion for users.
The S3 storage is also updated.
What is the reason for old names?
- Open clip hosts these models on HF Hub, and these are the names listed on hub.
Why new names?
- We want to give users a consistent experience dealing with [open clip model names](https://github.com/mlfoundations/open_clip#pretrained-model-interface). 
Model affected:
- ViT-B-32::laion2B-s34B-b79K -> ViT-B-32::laion2b-s34b-b79k
- ViT-L-14::laion2B-s32B-b82K -> ViT-L-14::laion2b-s32b-b82k
- ViT-H-14::laion2B-s32B-b79K -> ViT-H-14::laion2b-s32b-b79k
- ViT-g-14::laion2B-s12B-b42K -> ViT-g-14::laion2b-s12b-b42k
=> chore: use open clip naming convention for model names

docs/user-guides/finetuner.md
since finetuner updates their model repo, we need to update our docs. Also we need to specify `to_onnx=True` in `finetuner.fit()`
=> docs: update finetuner docs

.github/README-exec/torch.readme.md, docs/hosting/on-jcloud.md
Change according to https://jinaai.slack.com/archives/C046ZPCJ951/p1666606756311729
Links are tested
=> chore: change hub url from hub.jina.ai to cloud.jina.ai

docs/user-guides/benchmark.rst
Move choose-the-right-model section to the beginning for better reading experience
=> docs: move benchmark conclusion to beginning

client/clip_client/client.py, docs/user-guides/client.md, tests/test_client.py
`clip_client` by default collects all the results and returns them to users. In this pr, we enable the user to override this behavior by providing custom callbacks: `on_done`, `on_error`, and `on_always`. The usage of custom callbacks follows that of [Jina client](https://docs.jina.ai/fundamentals/client/client/#callbacks). 
We move all results collection logic to a default `on_done` callback, with or without async.
We also move the code that updates the progress bar to a default `on_always` callback, which wraps the user-defined `on_always` callback.
We do not provide a default `on_error` callback.
This PR also fixes a small bug that unboxes empty input for the rank endpoint to unify the behavior of all endpoints.
=> feat: allow custom callback in clip_client

.github/README-exec/onnx.readme.md, .github/README-exec/torch.readme.md, Dockerfiles/base.Dockerfile, Dockerfiles/cuda.Dockerfile
This pr installs the missing `transformers` package for torch & onnx executor docker images in hubble so that users can use M-CLIP models.
It also updates the hubble executor readme.
=> fix: install transformers for executor docker images

Dockerfiles/base.Dockerfile, Dockerfiles/cuda.Dockerfile
ViT-g/h and M-CLIP models usually take longer to download and have a high chance to timeout at the starting stage. This pr increases `timeout_ready` to 3000000ms
=> fix: increase timeout ready for executor docker images

docs/user-guides/client.md, docs/user-guides/server.md
Replace demo-cas.jina.ai everywhere in docs
=> chore: replace clip server address in docs

server/setup.py
This pr resolves the [issue](https://github.com/jina-ai/clip-as-service/issues/865). We fix the `torchvision` version to avoid this.
=> fix: torchvision version to avoid compatibility issue

README.md, client/setup.py, server/clip_server/executors/clip_onnx.py, server/clip_server/executors/clip_tensorrt.py, server/clip_server/executors/clip_torch.py, server/setup.py
Goals:
I will post a link to the completed Blog so that the usage of tracing is clear.
=> feat: add custom tracing spans with jina>=3.12.0

docs/user-guides/retriever.md
del null key.
otherwise，U will get this error. 
`TypeError: clip_server.executors.clip_torch.CLIPEncoder() argument after ** must be a mapping, not NoneType.`
=> chore: fix configuration file for the search flow

server/clip_server/model/model.py, server/setup.py, tests/test_server.py
This PR adapts recent changes introduced in open-clip-torch v2.8+
=> chore: bump open-clip-torch to v2.8.0

Dockerfiles/server.Dockerfile
This PR fixes the error in linked issue
=> fix: install pytorch cu116 for server docker image

.github/workflows/ci.yml, docs/user-guides/server.md, server/setup.py, tests/test_asyncio.py, tests/test_helper.py, tests/test_ranker.py, tests/test_search.py, tests/test_server.py, tests/test_simple.py, tests/test_tensorrt.py
There is a package conflict with `onnxruntime` and `onnxruntime-gpu` in setup. If we install both packages, we are not able to run onnx using gpu. Installing only `onnxruntime-gpu` enables clip_server to run both on CPU and GPU.
This PR also corrects the instructions on running docker image in different runtimes.
This PR also replaces the broken images in test files
Notes: onnxruntime is fixed at 1.13.1 to pass the test_ranker
nvidia-tensorrt is fixed at 8.4.1.5 to pass trt related tests
=> fix: onnx package conflict during setup

client/setup.py, docs/hosting/colab.md, docs/index.md, docs/user-guides/client.md, server/setup.py
Updating and maintainance of the docs.
=> docs: remove jina self-hosted parts
