- README.md
- app.py
- benchmark.py
- requirements.client.txt
- requirements.txt
- service/client.py
- service/server.py
- support cpu-only env, fix #4 
- optimize speed, serialization during transmission
- optimize concurrency
- update benchmark.py
- add some FAQ in readme
> Refactoring for optimizing speed and concurrency

- benchmark.py
- service/client.py
- fix benchmark in particular num_client
> Fix benchmark

- README.md
- app.py
- bert/extract_features.py
- service/server.py
- fix the bug when client cancels the request the server breaks
- add more pooling strategies, allowing user to choose which one to go
- add pooling layer selection
- add more configs in readme
- fix some typo
> Add more pooling strategies

- README.md
- service/server.py
- use random ipc address to avoid conflicts
- fix #28 logger problem
> Elmo like word embedding

- service/client.py
> fix python 2 encode problem

- README.md
> explain details about tokenization and fix #40

- README.md
- app.py
- bert/extract_features.py
Implementation of multi-layers added : 
It's now possible to specify several layers, and the resulting feature vector will be the concatenation of these layers.
From #34
> Multilayers support added

- README.md
- app.py
- service/server.py
> Add gpu config

- README.md
- example2.py
- example3.py
- service/client.py
- service/server.py
- each request from client now come with a req_id
- req_id is used to preserve the sending order
- refactor `encode_async()`, `fetch()` and `fetch_all()`
- add documentation for client
> improving the support of async encoding

- README.md
- bert/extract_features.py
- bert/modeling.py
- service/server.py
> add mask to reduce_mean, reduce_max and reduce_mean_max

- README.md
- client/README.md
- client/bert_serving/client/__init__.py
- docker/Dockerfile
- docker/entrypoint.sh
- server/README.md
- server/bert_serving/server/__init__.py
> Fix docker

- client/bert_serving/client/__init__.py
- server/bert_serving/server/__init__.py
fix #60  the classic slow-joiner problem for PUB-SUB pattern
> Fix concurrent client

- README.md
- client/README.md
- client/bert_serving/client/__init__.py
- example/example1.py
- example/example2.py
- example/example3.py
- example/example6.py
- example/example7.py
- server/README.md
- server/bert_serving/server/__init__.py
- server/bin/bert-serving-start
> adding flag to run on CPU/GPU

- README.md
- example/example1.py
- example/example2.py
- example/example3.py
- example/example6.py
- server/bert_serving/server/__init__.py
- server/bert_serving/server/bert/extract_features.py
- server/bin/bert-serving-start
though I don't observe any improvement on speed when [turning on XLA](https://www.tensorflow.org/xla/jit), but maybe it's just mine.
> add XLA support

- client/bert_serving/client/__init__.py
- server/bert_serving/server/bert/extract_features.py
- add mask when `pooling_strategy=NONE`, fix #119 
- refactor input check on client side, fix #121
> type check on the client

- README.md
- client/bert_serving/client/__init__.py
- server/bert_serving/server/__init__.py
- server/bert_serving/server/bert/extract_features.py
- server/bert_serving/server/bert/tokenization.py
> Refactor tokenization to support own tokenization

- server/bert_serving/server/__init__.py
- server/bert_serving/server/bert/extract_features.py
- server/bert_serving/server/helper.py
- server/bin/bert-serving-start
- freeze, optimize and export BERT model to a self-contained graph
- worker loads this graph and do computing
- add `-v` for checking server version
> Refactor estimator

- README.md
- server/bert_serving/server/__init__.py
- server/bert_serving/server/helper.py
- fix #51 
- move import inside process, may fix #99
> add device_map for manually assign gpu

- server/bert_serving/server/__init__.py
- server/bert_serving/server/zmq_decor.py
a further step and a more general solution based on #142 
this PR should solve the problem of when num_client > num_worker and one worker is pushing a super large batch causing all other workers job hanging in the queue.
> Refactor ventilator-worker socket

- benchmark.py
- client/bert_serving/client/__init__.py
- server/bert_serving/server/__init__.py
- server/bert_serving/server/helper.py
> Fix prefetch size for cpu

- README.md
- server/bert_serving/server/__init__.py
- server/bert_serving/server/bert/extract_features.py
- server/bert_serving/server/helper.py
- fix #169 , add `-mask_cls_sep` in server CLI
> masking [CLS] and [SEP] before pooling

- client/bert_serving/client/__init__.py
- server/bert_serving/server/__init__.py
- server/bert_serving/server/helper.py
fix timeout of client in #87 
- add a timeout decor
> fix client timeout issue in #87 

- client/bert_serving/client/__init__.py
- server/bert_serving/server/helper.py
- refactor logger for Windows compatibility as https://github.com/hanxiao/bert-as-service/issues/99#issuecomment-452769280 suggested, this should fix #99
> Fix windows logger

- benchmark.py
- client/bert_serving/client/__init__.py
- example/example4.py
- server/bert_serving/server/__init__.py
> move zmq linger to initialization

- client/bert_serving/client/__init__.py
- server/bert_serving/server/__init__.py
- server/bert_serving/server/bert/extract_features.py
- server/bert_serving/server/bert/modeling.py
- server/bert_serving/server/graph.py
- server/bert_serving/server/helper.py
> remove max_seq_len restriction on the server side

- client/bert_serving/client/__init__.py
- server/bert_serving/server/helper.py
> 269 fix bugs

- README.md
- server/bert_serving/server/__init__.py
- server/bert_serving/server/cli/__init__.py
- server/bert_serving/server/helper.py
- server/setup.py
> Add shutdown to cli

- server/bert_serving/server/__init__.py
- server/bert_serving/server/cli/__init__.py
- server/bert_serving/server/http.py
it will block the process until everything is ready, i.e. sink, worker is ready
> add ready signal to BertServer

- server/bert_serving/server/http.py
> fix http event error

- example/example7.py
Fix example7 (PCA visualization) error related to namedtuple. Tested with bert-as-service v1.8.9.
> fix example7

- server/bert_serving/server/__init__.py
Fix small job not returned bug when SINK receive job done msg earlier than job register msg
When several small job coming simultaneously, for some job, job done msg received by SINK earlier than the job register. This would cause SinkJob.add_embedded when check sum is still 0, and the job will never be send back. It is easy to reproduce when you send 8 small job at same time. As the log shown below , there are 3 'send back' but 8 'job done' log.
```
ARG   VALUE
__________________________________________________
ckpt_name = bert_model.ckpt
config_name = bert_config.json
cors = *
cpu = False
device_map = [2]
do_lower_case = True
fixed_embed_length = False
fp16 = False
gpu_memory_fraction = 0.5
graph_tmp_dir = None
http_max_connect = 10
http_port = None
mask_cls_sep = False
max_batch_size = …
```
> [BUGFIX]fix small job not returned bug when SINK receive job done msg earlier than job register msg

- docs/tutorial/simple-search.rst
This PR fixes an issue with connecting client to the server.
> updated in/out ports to match the default values

- server/bert_serving/server/graph.py
- server/bert_serving/server/helper.py
Hey, @hanxiao ,  I added CLASSIFICATION strategy to get the probabilities for classification problems
according to [How to get probability from a finetuned classify model · Issue #213 · hanxiao/bert-as-service](https://github.com/hanxiao/bert-as-service/issues/213). This works pretty well in my project. Please have a look!
> Add classification pooling strategy

- server/bert_serving/server/graph.py
Similar to the recent change for supporting classification as a pooling strategy, I have a PR that for regression tasks.
I hope this helps the community.
> Add regression pooling strategy

- example/example5.py
- example/example6.py
- server/bert_serving/server/bert/tokenization.py
- server/bert_serving/server/helper.py
tf.logging no longer exists in tensorflow 2.x.
> tf.logging -> tf.compat.v1.logging

- README.md
This PR works closely with https://github.com/hanxiao/bert-as-service/pull/584
> modified the port 8001->8081 to match Vue.js demo

- docs/user-guides/server.md
- server/clip_server/executors/clip_onnx.py
- server/clip_server/executors/clip_torch.py
> perf(server): use map_batch to overlap cpu gpu

- .gitignore
- scripts/black.sh
Add the same gitignore as in jina core
> feat: gitignore

- server/clip_server/__main__.py
This PR is blocked by https://github.com/jina-ai/jina/pull/4651
> fix: pass extra_search path

- docs/user-guides/server.md
Moved replicas outside of uses, correcting the indentation in the YAML file.
> Corrected replicas indentation in server.md

- client/setup.py
- server/setup.py
this pr sync with docarray to allow use to utilize the latest protobuf version
refer: https://github.com/jina-ai/docarray/pull/371
> chore: update protobuf version

- docs/hosting/on-jcloud.md
Add instructions on using GPU in Jcloud
> docs: update jcloud gpu usage

- docs/_templates/page.html
Fix the arrow buttons at the bottom of the page
Follow https://github.com/jina-ai/docarray/commit/afb84fb2d4195f04bb97e231a6f9e188f06d2307
> chore: fix docs website template

- docs/playground/searching.md
Add description for the searching playground. Explain what the demo is and what dataset we use.
> chore: add description for retrieval playground

- docs/user-guides/retriever.md
add documentation of memory profile for clip search
> docs: add memory profile

- docs/index.md
Hide changelog since we decide not to update
> chore: hide changelog in docs

- .github/workflows/ci.yml
- client/setup.py
- server/setup.py
This PR aims to prevent the installation of DocArrayV2, as we have encountered some compatibility issues that require further investigation. While this solution is temporary, it will allow us to ensure that our codebase remains stable and free from potential conflicts.
After conducting a thorough investigation of the compatibility of DocArrayV2, we will determine the best course of action moving forward. Until then, we appreciate your patience and understanding as we work to maintain the integrity of our codebase.
> fix: fix docarray at v1

- server/clip_server/model/clip.py
- server/setup.py
This PR adds the ability for Pillow to open AVIF images.
> Add AVIF support to CLIP server
